"""The 27 seed IAM/Okta features. Ported 1:1 from the original Next.js app's
lib/db/seed-data.ts — same names, slugs, and content, so the catalog is
identical regardless of which backend renders it.

Each entry is a dict matching the columns features.upsert_feature() expects:
name, slug, description, category, okta_capability, protocols, agent_type,
use_cases, security_considerations, related_feature_slugs.
"""

SEED_FEATURES = [
    {
        "name": "Single Sign-On (SSO)",
        "slug": "sso",
        "description": "Lets a user authenticate once and gain access to multiple independent applications without re-entering credentials for each one.",
        "category": "Authentication",
        "okta_capability": "Okta SSO / App Catalog",
        "protocols": ["SAML", "OIDC"],
        "agent_type": "None (browser redirect flow)",
        "use_cases": [
            "One login for email, CRM, and internal tools",
            "Reducing password fatigue and reset tickets",
            "Central place to enable/disable app access",
        ],
        "security_considerations": [
            "SSO becomes a single point of failure — protect the IdP account heavily",
            "Pair with strong MFA since one credential now unlocks everything",
        ],
        "related_feature_slugs": ["saml", "oidc", "application-assignment"],
    },
    {
        "name": "SAML",
        "slug": "saml",
        "description": "An XML-based standard for exchanging authentication and authorization data between an identity provider (Okta) and a service provider (the target app).",
        "category": "Federation",
        "okta_capability": "Okta SSO (SAML app integrations)",
        "protocols": ["SAML 2.0"],
        "agent_type": "Service Provider / Identity Provider handshake (no local agent)",
        "use_cases": [
            "Federating enterprise SaaS apps that predate OIDC",
            "Passing user attributes (email, groups) to an app at login",
        ],
        "security_considerations": [
            "Validate signed assertions and check the audience/recipient fields",
            "Watch for XML signature wrapping attacks in custom SP implementations",
        ],
        "related_feature_slugs": ["sso", "application-assignment"],
    },
    {
        "name": "OIDC",
        "slug": "oidc",
        "description": "OpenID Connect adds an identity layer on top of OAuth 2.0, issuing an ID Token so applications can verify who the user is, not just what they can access.",
        "category": "Authentication",
        "okta_capability": "Okta OIDC app integrations / Authorization Server",
        "protocols": ["OIDC", "OAuth 2.0"],
        "agent_type": "None (front/back-channel token exchange)",
        "use_cases": [
            "Modern web and mobile app login",
            "Single-page apps using the Authorization Code flow with PKCE",
        ],
        "security_considerations": [
            "Always validate the ID token signature, issuer, audience, and expiry",
            "Use PKCE for public clients (SPAs, mobile) to prevent code interception",
        ],
        "related_feature_slugs": ["oauth2", "sso", "token-management"],
    },
    {
        "name": "OAuth 2.0",
        "slug": "oauth2",
        "description": "An authorization framework that lets an application obtain limited, scoped access to a resource on a user's behalf without handling their password.",
        "category": "Authorization",
        "okta_capability": "Okta Authorization Server",
        "protocols": ["OAuth 2.0"],
        "agent_type": "None (token-based delegation)",
        "use_cases": [
            "Granting a third-party app read-only calendar access",
            "Issuing access tokens for API-to-API calls",
        ],
        "security_considerations": [
            "Scope tokens as narrowly as possible (principle of least privilege)",
            "Avoid the deprecated Implicit flow; prefer Authorization Code + PKCE",
        ],
        "related_feature_slugs": ["oidc", "oauth21", "api-access-management"],
    },
    {
        "name": "OAuth 2.1",
        "slug": "oauth21",
        "description": "A consolidation of OAuth 2.0 best practices into a single spec: mandates PKCE for all clients, drops the Implicit and Password grants, and tightens redirect URI matching.",
        "category": "Authorization",
        "okta_capability": "Okta Authorization Server (modern grant types)",
        "protocols": ["OAuth 2.1"],
        "agent_type": "None (token-based delegation)",
        "use_cases": [
            "New client integrations that want a simplified, safer-by-default spec",
            "Hardening older OAuth 2.0 integrations against known pitfalls",
        ],
        "security_considerations": [
            "Exact-match redirect URIs instead of pattern matching",
            "No bearer tokens in URL query strings",
        ],
        "related_feature_slugs": ["oauth2", "token-management"],
    },
    {
        "name": "Multi-Factor Authentication (MFA)",
        "slug": "mfa",
        "description": "Requires a user to present two or more independent verification factors — something they know, have, or are — before granting access.",
        "category": "MFA",
        "okta_capability": "Okta Verify / MFA factors",
        "protocols": ["OIDC", "WebAuthn/FIDO2"],
        "agent_type": "Okta Verify (mobile/desktop authenticator app)",
        "use_cases": [
            "Blocking account takeover even if a password is phished",
            "Meeting compliance requirements for privileged access",
        ],
        "security_considerations": [
            "SMS/voice factors are phishable — prefer push, WebAuthn, or TOTP",
            "Guard against MFA fatigue attacks (accepting a push without checking)",
        ],
        "related_feature_slugs": ["adaptive-mfa", "passwordless", "risk-based-auth"],
    },
    {
        "name": "Adaptive MFA",
        "slug": "adaptive-mfa",
        "description": "Dynamically decides whether to prompt for an additional factor based on contextual signals like device, network, location, and behavior, rather than always challenging the user.",
        "category": "MFA",
        "okta_capability": "Okta Adaptive MFA (ThreatInsight, device context)",
        "protocols": ["OIDC"],
        "agent_type": "Okta Verify + risk engine (ThreatInsight)",
        "use_cases": [
            "Skipping a second factor on a known, trusted corporate laptop",
            "Forcing step-up auth when a login comes from a new country",
        ],
        "security_considerations": [
            "Tune risk thresholds carefully — too loose defeats the purpose, too strict frustrates users",
            "Log and review step-up triggers to catch tuning drift",
        ],
        "related_feature_slugs": ["mfa", "risk-based-auth", "authentication-policies"],
    },
    {
        "name": "Passwordless Authentication",
        "slug": "passwordless",
        "description": "Authenticates users with possession- or biometric-based factors (FIDO2 security keys, Okta FastPass, platform biometrics) instead of a memorized password.",
        "category": "Authentication",
        "okta_capability": "Okta FastPass / WebAuthn",
        "protocols": ["WebAuthn/FIDO2", "OIDC"],
        "agent_type": "Okta Verify (FastPass), platform authenticator",
        "use_cases": [
            "Removing phishable passwords entirely for high-risk roles",
            "Faster login on managed devices via biometric unlock",
        ],
        "security_considerations": [
            "Plan a recovery path for lost devices/keys that doesn't reintroduce weak factors",
            "Bind credentials to hardware where possible (attestation)",
        ],
        "related_feature_slugs": ["mfa", "device-trust"],
    },
    {
        "name": "Lifecycle Management",
        "slug": "lifecycle-management",
        "description": "Automates the end-to-end identity lifecycle — joiner, mover, leaver — so accounts and access are created, updated, and removed in step with HR events.",
        "category": "Provisioning",
        "okta_capability": "Okta Lifecycle Management",
        "protocols": ["SCIM"],
        "agent_type": "Okta Provisioning Agent / HR-driven connectors",
        "use_cases": [
            "Auto-creating app accounts the moment a new hire is added in the HRIS",
            "Instantly revoking every app account on termination",
        ],
        "security_considerations": [
            "Deprovisioning delay is one of the biggest sources of orphaned access",
            "Reconcile HRIS and IdP regularly to catch drift",
        ],
        "related_feature_slugs": ["user-provisioning", "deprovisioning", "scim"],
    },
    {
        "name": "User Provisioning",
        "slug": "user-provisioning",
        "description": "Automatically creates and updates user accounts in downstream applications based on identity data and group/app assignments in Okta.",
        "category": "Provisioning",
        "okta_capability": "Okta Provisioning (push groups/users)",
        "protocols": ["SCIM"],
        "agent_type": "Okta SCIM connector / on-prem provisioning agent",
        "use_cases": [
            "Creating a Salesforce account automatically when assigned",
            "Keeping profile attributes (title, department) in sync across apps",
        ],
        "security_considerations": [
            "Validate attribute mappings so sensitive fields aren't over-shared",
            "Restrict which admins can change provisioning rules",
        ],
        "related_feature_slugs": ["deprovisioning", "scim", "lifecycle-management"],
    },
    {
        "name": "Deprovisioning",
        "slug": "deprovisioning",
        "description": "Removes or suspends a user's access across connected applications, typically triggered automatically by termination or role change.",
        "category": "Provisioning",
        "okta_capability": "Okta Lifecycle Management (deactivate/suspend)",
        "protocols": ["SCIM"],
        "agent_type": "Okta SCIM connector / on-prem provisioning agent",
        "use_cases": [
            "Immediately cutting off access when an employee is terminated",
            "Suspending (not deleting) accounts during a leave of absence",
        ],
        "security_considerations": [
            "Confirm downstream apps actually honor the deactivation call",
            "Retain an audit trail of what was revoked and when",
        ],
        "related_feature_slugs": ["user-provisioning", "lifecycle-management"],
    },
    {
        "name": "SCIM",
        "slug": "scim",
        "description": "System for Cross-domain Identity Management: a REST/JSON standard for automating the exchange of user and group identity data between Okta and target systems.",
        "category": "Provisioning",
        "okta_capability": "Okta SCIM provisioning integrations",
        "protocols": ["SCIM 2.0", "REST/JSON over OAuth 2.0"],
        "agent_type": "SCIM connector (cloud) or provisioning agent (on-prem apps)",
        "use_cases": [
            "Standardizing how a SaaS vendor accepts provisioning events",
            "Bulk-syncing groups into a downstream app's own group model",
        ],
        "security_considerations": [
            "Secure the SCIM bearer token/OAuth client used for the connector",
            "Rate-limit and validate inbound SCIM payloads on the receiving app",
        ],
        "related_feature_slugs": ["user-provisioning", "deprovisioning", "universal-directory"],
    },
    {
        "name": "Universal Directory",
        "slug": "universal-directory",
        "description": "Okta's flexible directory that stores and normalizes identity data from multiple sources (AD, LDAP, HR systems, apps) into a single profile per user.",
        "category": "Provisioning",
        "okta_capability": "Okta Universal Directory",
        "protocols": ["LDAP", "SCIM", "REST"],
        "agent_type": "Okta AD/LDAP Agent",
        "use_cases": [
            "Combining an on-prem AD profile with cloud HR attributes",
            "Mapping and transforming attributes per downstream app",
        ],
        "security_considerations": [
            "Attribute mapping mistakes can leak sensitive HR data to the wrong app",
            "Keep the on-prem directory agent patched and least-privileged",
        ],
        "related_feature_slugs": ["scim", "groups", "user-provisioning"],
    },
    {
        "name": "Groups",
        "slug": "groups",
        "description": "Collections of users used to organize access — assigning an entire group to an application or policy instead of managing users one by one.",
        "category": "Authorization",
        "okta_capability": "Okta Groups",
        "protocols": ["SCIM"],
        "agent_type": "None (directory construct)",
        "use_cases": [
            "Assigning all of Finance to the expense-reporting app",
            "Layering access policies on top of a department group",
        ],
        "security_considerations": [
            "Group sprawl makes access reviews harder — periodically prune unused groups",
            "Avoid nesting groups so deeply that effective access becomes opaque",
        ],
        "related_feature_slugs": ["group-rules", "application-assignment", "universal-directory"],
    },
    {
        "name": "Group Rules",
        "slug": "group-rules",
        "description": "Expression-based rules that automatically add or remove users from a group based on profile attributes, keeping membership current without manual work.",
        "category": "Authorization",
        "okta_capability": "Okta Group Rules (Okta Expression Language)",
        "protocols": ["N/A (policy engine, not a wire protocol)"],
        "agent_type": "None (evaluated by Okta's rules engine)",
        "use_cases": [
            "Auto-adding anyone with department = 'Engineering' to the Eng group",
            "Removing contractors from privileged groups when their end date passes",
        ],
        "security_considerations": [
            "Test rule logic in a sandbox — a bad rule can grant access org-wide",
            "Review rules that touch privileged or admin groups regularly",
        ],
        "related_feature_slugs": ["groups", "access-policies"],
    },
    {
        "name": "Application Assignment",
        "slug": "application-assignment",
        "description": "The mechanism for granting a user or group access to a specific application, which drives both SSO tile visibility and provisioning.",
        "category": "Authorization",
        "okta_capability": "Okta App Assignment",
        "protocols": ["SAML", "OIDC", "SCIM"],
        "agent_type": "Depends on app integration type",
        "use_cases": [
            "Giving the Sales group access to the CRM app",
            "Directly assigning a one-off app to a single contractor",
        ],
        "security_considerations": [
            "Prefer group-based over individual assignment for auditability",
            "Review direct (individual) assignments periodically — they bypass group governance",
        ],
        "related_feature_slugs": ["groups", "sso", "access-requests"],
    },
    {
        "name": "Access Policies",
        "slug": "access-policies",
        "description": "Org-wide or app-specific rules that define the conditions (network, device, group) under which access to a resource is allowed, denied, or challenged.",
        "category": "Identity Governance",
        "okta_capability": "Okta Sign-On Policies",
        "protocols": ["OIDC"],
        "agent_type": "None (policy engine)",
        "use_cases": [
            "Blocking logins to a sensitive app from outside the corporate network",
            "Requiring a managed device for access to finance systems",
        ],
        "security_considerations": [
            "Order policies carefully — the first matching rule wins",
            "Have a break-glass exception path so a bad policy doesn't lock everyone out",
        ],
        "related_feature_slugs": ["authentication-policies", "device-trust", "risk-based-auth"],
    },
    {
        "name": "Authentication Policies",
        "slug": "authentication-policies",
        "description": "App-level rules that specify which authenticators and factors are required to sign in, layered on top of the broader org access policy.",
        "category": "Identity Governance",
        "okta_capability": "Okta Authentication Policies",
        "protocols": ["OIDC"],
        "agent_type": "None (policy engine)",
        "use_cases": [
            "Requiring phishing-resistant MFA specifically for the admin console",
            "Allowing a lower-friction factor for a low-risk internal wiki",
        ],
        "security_considerations": [
            "Align policy strictness with the actual sensitivity of the app",
            "Audit policy changes — they directly change the org's risk posture",
        ],
        "related_feature_slugs": ["access-policies", "adaptive-mfa", "mfa"],
    },
    {
        "name": "API Access Management",
        "slug": "api-access-management",
        "description": "Okta's capability for issuing and validating OAuth 2.0 access tokens so custom and third-party APIs can enforce scoped, centrally-managed authorization.",
        "category": "API Security",
        "okta_capability": "Okta API Access Management (Custom Authorization Servers)",
        "protocols": ["OAuth 2.0", "JWT"],
        "agent_type": "None (token issuance and introspection)",
        "use_cases": [
            "Protecting an internal microservice with scoped access tokens",
            "Issuing machine-to-machine tokens via the Client Credentials grant",
        ],
        "security_considerations": [
            "Validate tokens on every API call (signature, audience, scope, expiry)",
            "Rotate signing keys and support key rollover (JWKS) without downtime",
        ],
        "related_feature_slugs": ["oauth2", "token-management"],
    },
    {
        "name": "Token Management",
        "slug": "token-management",
        "description": "Covers the issuance, lifetime, refresh, and revocation of access tokens, ID tokens, and refresh tokens used across OAuth 2.0/OIDC flows.",
        "category": "API Security",
        "okta_capability": "Okta Authorization Server (token lifetime policies)",
        "protocols": ["OAuth 2.0", "OIDC", "JWT"],
        "agent_type": "None (token lifecycle)",
        "use_cases": [
            "Setting short-lived access tokens with silent refresh for a SPA",
            "Revoking all tokens for a user immediately after a security incident",
        ],
        "security_considerations": [
            "Store refresh tokens securely (never in localStorage for browser apps)",
            "Implement revocation checks for high-sensitivity operations",
        ],
        "related_feature_slugs": ["oidc", "oauth2", "api-access-management"],
    },
    {
        "name": "Workflows",
        "slug": "workflows",
        "description": "A no-code automation builder for identity processes — chaining together triggers and actions across Okta and third-party systems without custom scripts.",
        "category": "Identity Governance",
        "okta_capability": "Okta Workflows",
        "protocols": ["REST", "SCIM (as connector actions)"],
        "agent_type": "None (cloud-hosted automation runtime)",
        "use_cases": [
            "Automatically opening a ticket when a high-risk access request is made",
            "Chaining a Slack notification into an offboarding process",
        ],
        "security_considerations": [
            "Workflows can hold powerful credentials — scope and review connector permissions",
            "Version and test flows before promoting them to production",
        ],
        "related_feature_slugs": ["access-requests", "lifecycle-management"],
    },
    {
        "name": "Device Trust",
        "slug": "device-trust",
        "description": "Evaluates whether the device used to sign in is managed, healthy, and compliant, and factors that into access decisions.",
        "category": "Security",
        "okta_capability": "Okta Device Trust (managed device / device assurance)",
        "protocols": ["OIDC", "mTLS (device certificates)"],
        "agent_type": "Okta Verify + MDM integration (Jamf, Intune)",
        "use_cases": [
            "Requiring a managed laptop for access to source code repos",
            "Blocking logins from jailbroken/rooted mobile devices",
        ],
        "security_considerations": [
            "Device posture checks are only as good as the MDM data feeding them",
            "Have a documented exception process for BYOD edge cases",
        ],
        "related_feature_slugs": ["passwordless", "access-policies", "risk-based-auth"],
    },
    {
        "name": "Risk-Based Authentication",
        "slug": "risk-based-auth",
        "description": "Continuously scores sign-in risk using signals like IP reputation, impossible travel, and anomalous behavior, then adjusts the required authentication strength.",
        "category": "Security",
        "okta_capability": "Okta ThreatInsight / Behavior Detection",
        "protocols": ["OIDC"],
        "agent_type": "Risk engine (ThreatInsight)",
        "use_cases": [
            "Stepping up to MFA when a login pattern looks like credential stuffing",
            "Auto-blocking sign-ins from known malicious IP ranges",
        ],
        "security_considerations": [
            "False positives can lock out legitimate traveling users — tune carefully",
            "Feed risk signals into logging for post-incident investigation",
        ],
        "related_feature_slugs": ["adaptive-mfa", "device-trust", "access-policies"],
    },
    {
        "name": "Identity Governance",
        "slug": "identity-governance",
        "description": "The umbrella discipline of ensuring the right people have the right access at the right time, through access reviews, certifications, and policy enforcement.",
        "category": "Identity Governance",
        "okta_capability": "Okta Identity Governance (OIG)",
        "protocols": ["SCIM", "REST"],
        "agent_type": "None (governance workflows on top of directory data)",
        "use_cases": [
            "Running a quarterly access certification for a finance app",
            "Detecting and remediating segregation-of-duties conflicts",
        ],
        "security_considerations": [
            "Certifications are only effective if reviewers actually scrutinize entries",
            "Track remediation to completion, not just review completion",
        ],
        "related_feature_slugs": ["access-requests", "access-policies"],
    },
    {
        "name": "Access Requests",
        "slug": "access-requests",
        "description": "A self-service workflow letting users request access to an app or group, routed through approval and (optionally) time-bound grants.",
        "category": "Identity Governance",
        "okta_capability": "Okta Identity Governance — Access Requests",
        "protocols": ["REST", "SCIM (grant fulfillment)"],
        "agent_type": "None (governance workflow)",
        "use_cases": [
            "Requesting temporary access to a production database for an incident",
            "Requesting a new app when starting a cross-team project",
        ],
        "security_considerations": [
            "Prefer time-bound grants over permanent access for one-off needs",
            "Ensure approvers have enough context to make an informed decision",
        ],
        "related_feature_slugs": ["identity-governance", "application-assignment", "workflows"],
    },
    {
        "name": "Okta MCP Server (Agentic Access)",
        "slug": "okta-mcp-server",
        "description": "A Model Context Protocol server that exposes Okta's management APIs as structured tools an AI agent (like Claude) can call on a user's behalf, under explicit scopes.",
        "category": "Agentic AI",
        "okta_capability": "Okta Management API, exposed via MCP tools",
        "protocols": ["MCP", "OAuth 2.0", "REST"],
        "agent_type": "MCP server (tool-calling agent bridge)",
        "use_cases": [
            "'Why don't I have access to Salesforce?' answered by an agent that queries assignments",
            "An agent submitting an access request on the user's behalf via a governed tool call",
        ],
        "security_considerations": [
            "Every MCP tool call should carry the end user's own scoped token, not a blanket admin credential",
            "Log every agent-initiated action with the same rigor as a human admin action",
        ],
        "related_feature_slugs": ["api-access-management", "access-requests", "identity-governance"],
    },
    {
        "name": "Conversational Access Copilot",
        "slug": "conversational-access-copilot",
        "description": "A chat interface (future Claude integration) that lets employees ask natural-language questions about their own access and, where policy allows, take governed actions.",
        "category": "Agentic AI",
        "okta_capability": "Claude + Okta MCP Server (planned)",
        "protocols": ["MCP", "OIDC", "OAuth 2.0"],
        "agent_type": "LLM agent (Claude) calling MCP tools",
        "use_cases": [
            "\"What groups am I assigned to?\"",
            "\"Why did my MFA registration fail?\"",
            "\"What role do I need for this application?\"",
        ],
        "security_considerations": [
            "Constrain the agent to read-only tools until write actions are explicitly reviewed",
            "Never let the agent see or handle raw credentials/secrets",
        ],
        "related_feature_slugs": ["okta-mcp-server", "access-requests"],
    },
]
